const DUPLICATE_MOBILE_ERROR = require('./DUPLICATE_MOBILE_ERROR');
const MOBILE_CANT_UPDATE = require('./MOBILE_CANT_UPDATE');
const INPUT_FORMAT_ERROR = require('./INPUT_FORMAT_ERROR');
const UNAUTHORIZED_ACCESS = require('./UNAUTHORIZED_ACCESS');
const DATA_BASE_ERROR = require('./DATA_BASE_ERROR');
const SCHEMA_VALIDATION_ERROR = require('./SCHEMA_VALIDATION_ERROR');
const VERIFY_OTP_ERROR = require('./VERIFY_OTP_ERROR');

module.exports = {
  DUPLICATE_MOBILE_ERROR,
  INPUT_FORMAT_ERROR,
  UNAUTHORIZED_ACCESS,
  DATA_BASE_ERROR,
  MOBILE_CANT_UPDATE,
  SCHEMA_VALIDATION_ERROR,
  VERIFY_OTP_ERROR,
};
